package main

const hRpcStubCodeHClient = `
// This file is generated by tool, DONT EDIT IT
// Source: [[{{.SourceFile}}]]


namespace {{.PackageName}} {

class IMessageDispatcher {
public:
	virtual ~IMessageDispatcher() = default;
	virtual void foo() = 0;
	virtual int bar() = 0;
};
	
class FDispatcherStub {
public:
	FDispatcherStub(IMessageDispatcher *md);
	void DoDispatch(const TArray<uint8>& msg) const;
private:
	TSharedPtr<IMessageDispatcher> Mdref;
};
`

const hRpcStubCodeCppClient = `
// This file is generated by tool, DONT EDIT IT
// Source: [[{{.SourceFile}}]]

namespace {{.PackageName}} {

DispatcherStub::FDispatcherStub(IMessageDispatcher *md): Mdref(md) {

}
	
void DispatcherStub::DoDispatch(const TArray<uint8>& msg) const {
	game::Package pkg;
	pkg.ParseFromArray(msg.GetData(), msg.Num());
	if (pkg.sessionid() > 0)
	{
		//assert route==""
		return;
	}

	auto route = pkg.route();
	auto data = pkg.data();
	if (route == "Enter")
	{
		
	}
	else if (route == "Leave")
	{
		
	}
};
`
